name: Publish to GitHub Pages

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn install

      - name: Build and Deploy
        run: |
          yarn build-storybook
        env:
          NODE_ENV: production

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch to deploy to
          FOLDER: storybook-static # The folder containing your built static site

  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs: ['build']
    if: always()

    steps:
      - name: Notify Slack on Success
        if: needs.build.result == 'success'
        uses: 8398a7/action-slack@v3
        with:
          status: success
          channel: '#notifications-dev'
          text: ':white_check_mark: GitHub Pages deployment succeeded!'
          fields: repo,message,commit,author,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack on Failure
        if: needs.build.result == 'failure'
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          channel: '#notifications-dev'
          text: ':x: GitHub Pages deployment failed!'
          fields: repo,message,commit,author,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
